# Generated by Django 2.2 on 2020-01-04 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(max_length=20)),
                ('device_model', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=15)),
                ('endpoint', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('GET', 'GET'), ('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], max_length=10)),
                ('body', models.CharField(blank=True, max_length=200)),
                ('device_model', models.ManyToManyField(related_name='command', to='devices.DevicesModel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=15)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_port', models.IntegerField()),
                ('device_model', models.ManyToManyField(to='devices.DevicesModel')),
                ('user', models.ManyToManyField(related_name='find_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
