# Generated by Django 2.2 on 2020-01-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommands',
            name='device_model',
            field=models.ManyToManyField(to='devices.DevicesModel'),
        ),
    ]
